version: '3.8'

services:
  ltff:
    image: ghcr.io/serpicroon/let-the-feeds-fly:latest
    container_name: let-the-feeds-fly
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - LOG_LEVEL=INFO
      - DATABASE=/data/ltff.db
      - HTTP_TIMEOUT=60.0
      - CLEANUP_AFTER_DAYS=60
    restart: unless-stopped
